name: iOS Starter Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Swift Package Manager dependencies
      - name: Resolve Swift Package Manager dependencies
        run: swift package resolve
        working-directory: ./iOSApp

      # Build the project
      - name: Build project
        run: xcodebuild build -scheme YourAppScheme -project ./iOSApp/YourAppProject.xcodeproj

      # Run tests
      - name: Run tests
        run: xcodebuild test -scheme YourAppScheme -project ./iOSApp/YourAppProject.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest'
